pipeline:
  name: Build hello-java-harness
  identifier: Build_chuckaude_org_hello_java_harness_1757027527903
  projectIdentifier: hellojava
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1757027501945
        repoName: chuckaude-org/hello-java-harness
        build: <+input>
