pipeline:
  name: Build hello-java-harness
  identifier: Build_chuckaude_org_hello_java_harness_1757027527903
  projectIdentifier: hellojava
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3-eclipse-temurin-21
                    shell: Sh
                    command: mvn -B -DskipTests package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1757027501945
        repoName: chuckaude-org/hello-java-harness
        build: <+input>
