pipeline:
  name: hello-java-polaris
  identifier: hellojavapolaris
  projectIdentifier: hellojava
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: GitHub_OAuth
        repoName: hello-java-harness
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Maven_Build
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3-eclipse-temurin-21
                    shell: Sh
                    command: mvn -B -DskipTests package
